services:
  - type: web
    name: tlairways-app
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://tlairways-app.onrender.com
      - key: ADOBE_ANALYTICS_ENABLED
        value: true
      - key: ADOBE_ENVIRONMENT
        value: production
      - key: REACT_APP_AUTH0_DOMAIN
        value: dev-q6p3jrm5pbykuq23.us.auth0.com
      - key: REACT_APP_AUTH0_CLIENT_ID
        value: d6C2RT8TI6QwQyu2ouDS7U781HT3kF28
      - key: REACT_APP_AUTH0_AUDIENCE
        value: https://api.tlairways.com
      - key: REACT_APP_AUTH0_REDIRECT_URI
        value: https://tlairways-app.onrender.com
      - key: REACT_APP_AUTH0_SCOPE
        value: openid profile email
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - package.json
        - package-lock.json
        - render.yaml 