services:
  - type: web
    name: tlairways-app
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://tlairways-app.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - package.json
        - package-lock.json
        - render.yaml 